# Generated by Django 4.1.7 on 2023-04-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
