# Generated by Django 4.1.7 on 2023-05-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wishlist_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='selling_price',
        ),
    ]
