# Generated by Django 4.1.7 on 2023-04-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='instrument_purchase',
        ),
    ]
