# Generated by Django 4.1.7 on 2023-04-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_customer_instrument_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
