# Generated by Django 4.1.7 on 2023-04-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customer_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address_line',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='userName',
            new_name='username',
        ),
    ]
